---
- hosts: machine1
  remote_user: vagrant
  sudo: true

  vars:
  - version: 1.1

  vars_files:
  - ./vars/common.yml
  - ./vars/local_virtual_box.yml

  handlers:
  - include: ./handlers/jenkins.yml

  tasks:

  - name: Install basic packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - curl
      - software-properties-common

  - include: ./tasks/nodejs.yml
  - include: ./tasks/python.yml
  - include: ./tasks/java7.yml
  - include: ./tasks/ruby.yml

  - name: Install Sass
    command: gem install sass


  - include: ./tasks/jenkins.yml