---
- hosts: machine1
  remote_user: vagrant
  sudo: true

  vars:
  - version: 1.1

  vars_files:
  - ./vars/software_versions.yml
  - ./vars/local_virtual_box.yml

  tasks:

  - name: Install basic packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - npm
      - curl

  - name: Restart Jenkins
    sudo: yes
    command: java -jar {{ jenkins.cli_dest }} -s http://{{ jenkins_host }}:8080 safe-restart


  - include: ./tasks/python.yml
  - include: ./tasks/java7.yml
  - include: ./tasks/jenkins.yml